"""rename_quote_request_to_direct_order

Revision ID: 14b159f248ac
Revises: f10cf6fa2019
Create Date: 2026-02-02 14:21:06.702121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b159f248ac'
down_revision: Union[str, Sequence[str], None] = 'f10cf6fa2019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('vessel_id', sa.UUID(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.Enum('Methanol', 'Biofuel', 'LNG', 'Ammonia', 'LSMGO', name='fueltype', native_enum=False), nullable=False),
    sa.Column('quantity_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_window_start', sa.Date(), nullable=True),
    sa.Column('delivery_window_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Pending', 'Quoted', 'Negotiating', 'Confirmed', 'Rejected', 'Completed', name='directorderofferstatus', native_enum=False), nullable=False),
    sa.Column('awarded_supplier_id', sa.UUID(), nullable=True),
    sa.Column('final_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_price_per_mt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['awarded_supplier_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_order_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direct_order_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('price_per_mt_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_and_conditions', sa.String(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['direct_order_id'], ['direct_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quote_requests')
    op.drop_table('quote_offers')
    op.add_column('traceability_events', sa.Column('direct_order_id', sa.UUID(), nullable=True))
    op.drop_constraint('traceability_events_quote_id_fkey', 'traceability_events', type_='foreignkey')
    op.create_foreign_key(None, 'traceability_events', 'direct_orders', ['direct_order_id'], ['id'])
    op.drop_column('traceability_events', 'quote_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traceability_events', sa.Column('quote_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'traceability_events', type_='foreignkey')
    op.create_foreign_key('traceability_events_quote_id_fkey', 'traceability_events', 'quote_requests', ['quote_id'], ['id'])
    op.drop_column('traceability_events', 'direct_order_id')
    op.create_table('quote_offers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_per_mt_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('terms_and_conditions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['quote_requests.id'], name='quote_offers_request_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], name='quote_offers_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quote_offers_pkey')
    )
    op.create_table('quote_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vessel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('port_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('quantity_mt', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('delivery_window_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivery_window_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('awarded_supplier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('final_price_usd', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('final_price_per_mt', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['awarded_supplier_id'], ['organizations.id'], name='quote_requests_awarded_supplier_id_fkey'),
    sa.ForeignKeyConstraint(['buyer_id'], ['organizations.id'], name='quote_requests_buyer_id_fkey'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], name='quote_requests_port_id_fkey'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], name='quote_requests_vessel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quote_requests_pkey')
    )
    op.drop_table('direct_order_offers')
    op.drop_table('direct_orders')
    # ### end Alembic commands ###
