"""add_domain_to_organization

Revision ID: 63cbf0775d4d
Revises: c31aa85e9739
Create Date: 2026-01-31 20:32:49.578493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cbf0775d4d'
down_revision: Union[str, Sequence[str], None] = 'c31aa85e9739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('domain', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'domain')
    # ### end Alembic commands ###
