"""Add requested quantity and delivery date to RFQMatch

Revision ID: c5e4af769a3a
Revises: 148fa1ffb191
Create Date: 2026-02-01 14:56:31.651923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e4af769a3a'
down_revision: Union[str, Sequence[str], None] = '148fa1ffb191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfq_matches', sa.Column('requested_quantity_mt', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('rfq_matches', sa.Column('requested_delivery_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfq_matches', 'requested_delivery_date')
    op.drop_column('rfq_matches', 'requested_quantity_mt')
    # ### end Alembic commands ###
