"""Add QuoteOffer model

Revision ID: c8a8c986fb8c
Revises: ccef95a9c9a0
Create Date: 2026-01-30 03:07:29.016813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c8a8c986fb8c'
down_revision: Union[str, Sequence[str], None] = 'ccef95a9c9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('price_per_mt_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_and_conditions', sa.String(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['quote_requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vessels', sa.Column('previous_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    # op.create_index('idx_vessels_previous_location', 'vessels', ['previous_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_vessels_previous_location', table_name='vessels', postgresql_using='gist')
    # op.drop_column('vessels', 'previous_location')
    op.drop_table('quote_offers')
    # ### end Alembic commands ###
