"""add_rfq_models

Revision ID: ccef95a9c9a0
Revises: 411b38418aea
Create Date: 2026-01-28 01:52:01.113628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccef95a9c9a0'
down_revision: Union[str, Sequence[str], None] = '411b38418aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('fuel_grade', sa.Enum('CONVENTIONAL', 'GREEN', 'BIO', name='fuelgrade', native_enum=False), nullable=False),
    sa.Column('quantity_mt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_mt_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availability_window', sa.Enum('SPOT', 'Q1_2025', 'Q2_2025', 'Q3_2025', 'Q4_2025', 'Q1_2026', 'Q2_2026', 'Q3_2026', 'Q4_2026', 'FORWARD_2027', 'FORWARD_2028', name='availabilitywindow', native_enum=False), nullable=False),
    sa.Column('tier_label', sa.Enum('TIER_1_PRODUCER', 'MAJOR_TRADER', 'REGIONAL_SUPPLIER', 'INDEPENDENT', name='tierlabel', native_enum=False), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('is_verdaxis_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', name='listingstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfq_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'COMPLETED', 'CANCELLED', name='matchstatus', native_enum=False), nullable=False),
    sa.Column('buyer_accepted_terms_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_quantity_mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_price_per_mt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_total_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission_rate_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('commission_amount_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['public_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PAID', name='commissionstatus', native_enum=False), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['rfq_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissions')
    op.drop_table('rfq_matches')
    op.drop_table('public_listings')
    # ### end Alembic commands ###
